### ISSUE TITLE
could you empty the ram after each scan bruh

### ISSUE THREAD

**Issue by Leclowndu93150** [Minecraft-Malware-Prevention-Alliance/utilsdetector#4]

**Comment by jshbB** [comment]
Is low level things like that possible in Java?
Well we can create each thread for each scan, and leading to less ram usage perhaps?

**Comment by Leclowndu93150** [comment]
i have no clue how stuff work, but all i know is that the ram doesn't clear itself, there is a garbage collector right ?

**Comment by jshbB** [comment]
garbage collection happens automatically I think
